// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package hw

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockHDDControl creates a new instance of MockHDDControl. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHDDControl(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHDDControl {
	mock := &MockHDDControl{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHDDControl is an autogenerated mock type for the HDDControl type
type MockHDDControl struct {
	mock.Mock
}

type MockHDDControl_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHDDControl) EXPECT() *MockHDDControl_Expecter {
	return &MockHDDControl_Expecter{mock: &_m.Mock}
}

// GetState provides a mock function for the type MockHDDControl
func (_mock *MockHDDControl) GetState(dev string) (string, error) {
	ret := _mock.Called(dev)

	if len(ret) == 0 {
		panic("no return value specified for GetState")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(dev)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(dev)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(dev)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHDDControl_GetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetState'
type MockHDDControl_GetState_Call struct {
	*mock.Call
}

// GetState is a helper method to define mock.On call
//   - dev string
func (_e *MockHDDControl_Expecter) GetState(dev interface{}) *MockHDDControl_GetState_Call {
	return &MockHDDControl_GetState_Call{Call: _e.mock.On("GetState", dev)}
}

func (_c *MockHDDControl_GetState_Call) Run(run func(dev string)) *MockHDDControl_GetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHDDControl_GetState_Call) Return(s string, err error) *MockHDDControl_GetState_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockHDDControl_GetState_Call) RunAndReturn(run func(dev string) (string, error)) *MockHDDControl_GetState_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockHDDControl
func (_mock *MockHDDControl) List() ([]string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHDDControl_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockHDDControl_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *MockHDDControl_Expecter) List() *MockHDDControl_List_Call {
	return &MockHDDControl_List_Call{Call: _e.mock.On("List")}
}

func (_c *MockHDDControl_List_Call) Run(run func()) *MockHDDControl_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHDDControl_List_Call) Return(strings []string, err error) *MockHDDControl_List_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockHDDControl_List_Call) RunAndReturn(run func() ([]string, error)) *MockHDDControl_List_Call {
	_c.Call.Return(run)
	return _c
}

// SetStandbyTimeout provides a mock function for the type MockHDDControl
func (_mock *MockHDDControl) SetStandbyTimeout(dev string, value int) error {
	ret := _mock.Called(dev, value)

	if len(ret) == 0 {
		panic("no return value specified for SetStandbyTimeout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, int) error); ok {
		r0 = returnFunc(dev, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHDDControl_SetStandbyTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStandbyTimeout'
type MockHDDControl_SetStandbyTimeout_Call struct {
	*mock.Call
}

// SetStandbyTimeout is a helper method to define mock.On call
//   - dev string
//   - value int
func (_e *MockHDDControl_Expecter) SetStandbyTimeout(dev interface{}, value interface{}) *MockHDDControl_SetStandbyTimeout_Call {
	return &MockHDDControl_SetStandbyTimeout_Call{Call: _e.mock.On("SetStandbyTimeout", dev, value)}
}

func (_c *MockHDDControl_SetStandbyTimeout_Call) Run(run func(dev string, value int)) *MockHDDControl_SetStandbyTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHDDControl_SetStandbyTimeout_Call) Return(err error) *MockHDDControl_SetStandbyTimeout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHDDControl_SetStandbyTimeout_Call) RunAndReturn(run func(dev string, value int) error) *MockHDDControl_SetStandbyTimeout_Call {
	_c.Call.Return(run)
	return _c
}
